version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_eccomers
    restart: always
    environment:
      POSTGRES_DB: db_eccomers
      POSTGRES_USER: eccomers
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5444:5432"